[project]
name = "googlee"
version = "0.1.0"
description = "Hackathon"
requires-python = ">=3.10"

dependencies = [
    "google-adk>=1.22.0",
    "pillow>=12.1.0",
]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]

